[tool.poetry]
name = "sample"
version = "0.1.0"
description = ""
authors = ["olivierursushorribilis <ursusossforever@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.28.0"
aws-cdk-lib = "2.80.0"
boto3 = "1.26.120"
pyyaml = "5.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
